### ISSUE TITLE
Getting issues installing latest vui-validation

### ISSUE THREAD

**Issue by mdgbayly** [Brightspace/valence-ui-input#94]
Trying to npm install vui-validation 1.1.0 causes version conflicts with d2l-colors.
I think the issue is because the version of vui-input which usies d2l-colors ^2.1.0 has not been published to npm?

Works if you bower install vui-validation so maybe some weird npm/bower dependency resolution issue?

> vui-validation@1.1.0 postinstall C:\projects\qed-opt\node_modules\vui-validation
> bower install

bower vui-input#~1.6.0          cached https://github.com/Brightspace/valence-ui-input.git#1.6.2
bower vui-input#~1.6.0        validate 1.6.2 against https://github.com/Brightspace/valence-ui-input.git#~1.6.0
bower d2l-colors#~2.0.0         cached https://github.com/Brightspace/d2l-colors-ui.git#2.0.0
bower d2l-colors#~2.0.0       validate 2.0.0 against https://github.com/Brightspace/d2l-colors-ui.git#~2.0.0
bower d2l-colors#^2.1.0         cached https://github.com/Brightspace/d2l-colors-ui.git#2.1.0
bower d2l-colors#^2.1.0       validate 2.1.0 against https://github.com/Brightspace/d2l-colors-ui.git#^2.1.0
bower vui-focus#~0.7.1          cached https://github.com/Brightspace/valence-ui-focus.git#0.7.1
bower vui-focus#~0.7.1        validate 0.7.1 against https://github.com/Brightspace/valence-ui-focus.git#~0.7.1
bower polymer#^1.3.0            cached https://github.com/Polymer/polymer.git#1.6.1
bower polymer#^1.3.0          validate 1.6.1 against https://github.com/Polymer/polymer.git#^1.3.0
bower webcomponentsjs#^0.7.20   cached https://github.com/Polymer/webcomponentsjs.git#0.7.22
bower webcomponentsjs#^0.7.20 validate 0.7.22 against https://github.com/Polymer/webcomponentsjs.git#^0.7.20
bower                        ECONFLICT Unable to find suitable version for d2l-colors

**Comment by omsmith** [comment]
Yeah, installing _vui-validation_ from npm gets `d2l-colors: ~2.0.0` from the _bower.json_ at that version. Installing from bower gets you the latest in git. @ryantmer didn't bump the package.json when adding the _v1.1.1_ tag. So the publish failed https://travis-ci.org/Brightspace/valence-ui-validation.

**Comment by ryantmer** [comment]
Crap, did like 15 packages at once and totally missed this. I'll fix it, thanks @mdgbayly and @omsmith!

**Comment by dlockhart** [comment]
@ryantmer since the publish failed, you should be able to just delete the release and tag, update the version in package.json, then re-create the release.

**Comment by ryantmer** [comment]
@dlockhart alas, didn't think to do that, just created a new version :s

**Comment by dlockhart** [comment]
Cool that works too :)

**Comment by ryantmer** [comment]
Fixed in https://github.com/Brightspace/valence-ui-validation/commit/3f5beca9279513cb3de9c5394f5d48058c49a0fa - sorry about that, @mdgbayly!
